// Manifeste optionnel : libellés lisibles + regroupement par section pour l'affichage.
// Purement cosmétique — si une clé n'a pas d'entrée ici, elle s'affiche quand même
// (libellé = la clé technique, groupe = "Autres"). Un client sans manifeste défini
// fonctionne donc normalement, juste avec un affichage moins soigné.
export const MANIFEST = {
  hero_titre_ligne1: { label: 'Titre principal — ligne 1', groupe: 'Hero' },
  hero_titre_accent: { label: 'Titre principal — accroche', groupe: 'Hero' },
  hero_sous_titre: { label: 'Sous-titre', groupe: 'Hero' },

  prix_classique_creation: { label: 'Vitrine classique — prix création', groupe: 'Offre' },
  prix_classique_mensuel: { label: 'Vitrine classique — prix mensuel', groupe: 'Offre' },
  prix_classique_avantage_1: { label: 'Vitrine classique — avantage 1', groupe: 'Offre' },
  prix_classique_avantage_2: { label: 'Vitrine classique — avantage 2', groupe: 'Offre' },
  prix_classique_avantage_3: { label: 'Vitrine classique — avantage 3', groupe: 'Offre' },
  prix_classique_avantage_4: { label: 'Vitrine classique — avantage 4', groupe: 'Offre' },
  prix_classique_avantage_5: { label: 'Vitrine classique — avantage 5', groupe: 'Offre' },
  prix_classique_avantage_6: { label: 'Vitrine classique — avantage 6', groupe: 'Offre' },
  prix_classique_note: { label: 'Vitrine classique — note', groupe: 'Offre' },

  prix_ultra_creation: { label: 'Site animé — prix création', groupe: 'Offre' },
  prix_ultra_mensuel: { label: 'Site animé — prix mensuel', groupe: 'Offre' },
  prix_ultra_avantage_1: { label: 'Site animé — avantage 1', groupe: 'Offre' },
  prix_ultra_avantage_2: { label: 'Site animé — avantage 2', groupe: 'Offre' },
  prix_ultra_avantage_3: { label: 'Site animé — avantage 3', groupe: 'Offre' },
  prix_ultra_avantage_4: { label: 'Site animé — avantage 4', groupe: 'Offre' },
  prix_ultra_avantage_5: { label: 'Site animé — avantage 5', groupe: 'Offre' },
  prix_ultra_avantage_6: { label: 'Site animé — avantage 6', groupe: 'Offre' },
  prix_ultra_note: { label: 'Site animé — note', groupe: 'Offre' },

  prix_ecom_creation: { label: 'E-commerce — prix création', groupe: 'Offre' },
  prix_ecom_mensuel: { label: 'E-commerce — prix mensuel', groupe: 'Offre' },
  prix_ecom_avantage_1: { label: 'E-commerce — avantage 1', groupe: 'Offre' },
  prix_ecom_avantage_2: { label: 'E-commerce — avantage 2', groupe: 'Offre' },
  prix_ecom_avantage_3: { label: 'E-commerce — avantage 3', groupe: 'Offre' },
  prix_ecom_avantage_4: { label: 'E-commerce — avantage 4', groupe: 'Offre' },
  prix_ecom_avantage_5: { label: 'E-commerce — avantage 5', groupe: 'Offre' },
  prix_ecom_avantage_6: { label: 'E-commerce — avantage 6', groupe: 'Offre' },

  prix_premium_avantage_1: { label: 'Site ultra premium — avantage 1', groupe: 'Offre' },
  prix_premium_avantage_2: { label: 'Site ultra premium — avantage 2', groupe: 'Offre' },
  prix_premium_avantage_3: { label: 'Site ultra premium — avantage 3', groupe: 'Offre' },
  prix_premium_avantage_4: { label: 'Site ultra premium — avantage 4', groupe: 'Offre' },
  prix_premium_avantage_5: { label: 'Site ultra premium — avantage 5', groupe: 'Offre' },

  prix_chatbot_creation: { label: 'Option Assistant IA — prix création', groupe: 'Offre' },
  prix_chatbot_mensuel: { label: 'Option Assistant IA — prix mensuel', groupe: 'Offre' },
  prix_chatbot_avantage_1: { label: 'Option Assistant IA — avantage 1', groupe: 'Offre' },
  prix_chatbot_avantage_2: { label: 'Option Assistant IA — avantage 2', groupe: 'Offre' },
  prix_chatbot_avantage_3: { label: 'Option Assistant IA — avantage 3', groupe: 'Offre' },
  prix_chatbot_avantage_4: { label: 'Option Assistant IA — avantage 4', groupe: 'Offre' },

  prix_smsauto_creation: { label: 'Option SMS appel manqué — prix création', groupe: 'Offre' },
  prix_smsauto_mensuel: { label: 'Option SMS appel manqué — prix mensuel', groupe: 'Offre' },
  prix_smsauto_avantage_1: { label: 'Option SMS appel manqué — avantage 1', groupe: 'Offre' },
  prix_smsauto_avantage_2: { label: 'Option SMS appel manqué — avantage 2', groupe: 'Offre' },
  prix_smsauto_avantage_3: { label: 'Option SMS appel manqué — avantage 3', groupe: 'Offre' },
  prix_smsauto_avantage_4: { label: 'Option SMS appel manqué — avantage 4', groupe: 'Offre' },

  prix_packprint_creation: { label: 'Option Pack print — prix', groupe: 'Offre' },
  prix_packprint_avantage_1: { label: 'Option Pack print — avantage 1', groupe: 'Offre' },
  prix_packprint_avantage_2: { label: 'Option Pack print — avantage 2', groupe: 'Offre' },
  prix_packprint_avantage_3: { label: 'Option Pack print — avantage 3', groupe: 'Offre' },
  prix_packprint_avantage_4: { label: 'Option Pack print — avantage 4', groupe: 'Offre' },

  addon_avantage_1: { label: 'Autres services — ligne 1 (Fiche Google)', groupe: 'Offre' },
  addon_avantage_2: { label: 'Autres services — ligne 2 (Réseaux sociaux)', groupe: 'Offre' },
  addon_avantage_3: { label: 'Autres services — ligne 3 (Publicité en ligne)', groupe: 'Offre' },

  // Clés spécifiques à KSM Burger (site avec section "Pourquoi", "À propos",
  // horaires détaillés) — groupes réutilisés quand le sens correspond
  // (ex: "Pourquoi" ~ "Services"), nouveaux groupes sinon.
  pourquoi_1_desc: { label: 'Argument 1 — description', groupe: 'Services' },
  pourquoi_2_desc: { label: 'Argument 2 — description', groupe: 'Services' },
  pourquoi_3_desc: { label: 'Argument 3 — description', groupe: 'Services' },

  apropos_texte_1: { label: 'À propos — paragraphe 1', groupe: 'À propos' },
  apropos_texte_2: { label: 'À propos — paragraphe 2', groupe: 'À propos' },
  apropos_image: { label: 'À propos — photo', groupe: 'À propos' },

  footer_description: { label: 'Footer — texte de présentation', groupe: 'Footer' },

  horaires_lundi: { label: 'Horaires — lundi', groupe: 'Horaires' },
  horaires_mardi: { label: 'Horaires — mardi', groupe: 'Horaires' },
  horaires_mercredi: { label: 'Horaires — mercredi', groupe: 'Horaires' },
  horaires_jeudi: { label: 'Horaires — jeudi', groupe: 'Horaires' },
  horaires_vendredi: { label: 'Horaires — vendredi', groupe: 'Horaires' },
  horaires_samedi: { label: 'Horaires — samedi', groupe: 'Horaires' },
  horaires_dimanche: { label: 'Horaires — dimanche', groupe: 'Horaires' },

  // Clés spécifiques à AZROW (entreprise du bâtiment inclusive, Montpellier)
  // Noms de clés préfixés/spécifiques pour éviter toute collision avec les clés
  // génériques service_X_desc / stat_X_valeur déjà utilisées par le site LocWeb lui-même.
  service_electricite_desc: { label: 'Électricité — description', groupe: 'Services' },
  service_bati_ancien_desc: { label: 'Bâti ancien — description', groupe: 'Services' },
  service_eco_construction_desc: { label: 'Éco-construction — description', groupe: 'Services' },
  service_plomberie_desc: { label: 'Plomberie — description', groupe: 'Services' },
  service_carrelage_desc: { label: 'Carrelage — description', groupe: 'Services' },
  engagement_texte_1: { label: 'Engagement — paragraphe 1', groupe: 'Engagement' },
  engagement_image_1: { label: 'Engagement — photo 1', groupe: 'Engagement' },
  engagement_texte_2: { label: 'Engagement — paragraphe 2', groupe: 'Engagement' },
  engagement_image_2: { label: 'Engagement — photo 2', groupe: 'Engagement' },
  stat_metiers_valeur: { label: 'Chiffre clé — nb corps de métier', groupe: 'Preuve sociale' },
  stat_metiers_label: { label: 'Chiffre clé — légende (métiers)', groupe: 'Preuve sociale' },
  stat_ville_valeur: { label: 'Chiffre clé — ville', groupe: 'Preuve sociale' },
  stat_ville_label: { label: 'Chiffre clé — légende (ville)', groupe: 'Preuve sociale' },
  stat_inclusif_valeur: { label: 'Chiffre clé — taux inclusion', groupe: 'Preuve sociale' },
  stat_inclusif_label: { label: 'Chiffre clé — légende (inclusion)', groupe: 'Preuve sociale' },
  stat_devis_valeur: { label: 'Chiffre clé — devis', groupe: 'Preuve sociale' },
  stat_devis_label: { label: 'Chiffre clé — légende (devis)', groupe: 'Preuve sociale' },
  contact_telephone: { label: 'Téléphone de contact', groupe: 'Footer' },
  contact_email: { label: 'Email de contact', groupe: 'Footer' },

  // Clés spécifiques à Maison Verrier (site test premium tier 3, rénovation bâti ancien)
  service_charpente_desc: { label: 'Charpente — description', groupe: 'Services' },
  service_renovation_desc: { label: 'Rénovation bâti ancien — description', groupe: 'Services' },
  service_toiture_desc: { label: 'Toiture — description', groupe: 'Services' },
  service_maconnerie_desc: { label: 'Maçonnerie pierre — description', groupe: 'Services' },
  service_menuiserie_desc: { label: 'Menuiserie sur mesure — description', groupe: 'Services' },
  service_suivi_desc: { label: 'Suivi de chantier — description', groupe: 'Services' },
  expertise_texte_1: { label: 'Expertise — paragraphe 1', groupe: 'Expertise' },
  expertise_texte_2: { label: 'Expertise — paragraphe 2', groupe: 'Expertise' },

  /* ---- Auto Wash 34 (Beziers) ---- */
  hero_surtitre: { label: 'Hero — surtitre', groupe: 'Hero' },
  hero_titre: { label: 'Hero — titre principal', groupe: 'Hero' },
  hero_accroche: { label: 'Hero — accroche', groupe: 'Hero' },
  hero_mots: { label: "Hero — mots qui tournent (separes par des virgules)", groupe: 'Hero' },
  hero_photo_1: { label: 'Hero — photo 1 du diaporama', groupe: 'Hero' },
  hero_photo_2: { label: 'Hero — photo 2 du diaporama', groupe: 'Hero' },
  hero_photo_3: { label: 'Hero — photo 3 du diaporama', groupe: 'Hero' },
  formules_titre: { label: 'Formules — titre', groupe: 'Services' },
  formules_intro: { label: 'Formules — introduction', groupe: 'Services' },
  formule_1_titre: { label: 'Formule 1 — nom', groupe: 'Services' },
  formule_1_liste: { label: 'Formule 1 — ce qui est inclus', groupe: 'Services' },
  formule_2_titre: { label: 'Formule 2 — nom', groupe: 'Services' },
  formule_2_liste: { label: 'Formule 2 — ce qui est inclus', groupe: 'Services' },
  formule_3_titre: { label: 'Formule 3 — nom', groupe: 'Services' },
  formule_3_liste: { label: 'Formule 3 — ce qui est inclus', groupe: 'Services' },
  bande_photo: { label: 'Bande — photo de fond', groupe: 'Preuve sociale' },
  citation_texte: { label: 'Bande — phrase mise en avant', groupe: 'Preuve sociale' },
  citation_auteur: { label: 'Bande — signature', groupe: 'Preuve sociale' },
  deroule_titre: { label: 'Deroulement — titre', groupe: 'Engagement' },
  deroule_intro: { label: 'Deroulement — introduction', groupe: 'Engagement' },
  etape_1_titre: { label: 'Etape 1 — titre', groupe: 'Engagement' },
  etape_1_texte: { label: 'Etape 1 — texte', groupe: 'Engagement' },
  etape_2_titre: { label: 'Etape 2 — titre', groupe: 'Engagement' },
  etape_2_texte: { label: 'Etape 2 — texte', groupe: 'Engagement' },
  etape_3_titre: { label: 'Etape 3 — titre', groupe: 'Engagement' },
  etape_3_texte: { label: 'Etape 3 — texte', groupe: 'Engagement' },
  zone_titre: { label: 'Zone desservie — titre', groupe: 'A propos' },
  zone_intro: { label: 'Zone desservie — introduction', groupe: 'A propos' },
  zone_communes: { label: 'Zone desservie — liste des communes', groupe: 'A propos' },
  contact_titre: { label: 'Contact — titre', groupe: 'Footer' },
  contact_intro: { label: 'Contact — introduction', groupe: 'Footer' },
  contact_adresse: { label: 'Adresse', groupe: 'Footer' },
  contact_horaires: { label: 'Horaires', groupe: 'Horaires' },

  /* ---- Auto Wash 34 : bande d'appel ----
     Libelles entre GUILLEMETS et non entre apostrophes : « Bande
     d'appel » en contient une, qui fermait la chaine au milieu. */
  appel_photo: { label: "Bande d'appel — photo de fond", groupe: 'Engagement' },
  appel_surtitre: { label: "Bande d'appel — surtitre", groupe: 'Engagement' },
  appel_titre: { label: "Bande d'appel — titre", groupe: 'Engagement' },
  appel_texte: { label: "Bande d'appel — texte", groupe: 'Engagement' },

  /* ---- Auto Wash 34 : textiles ---- */
  formule_4_titre: { label: "Formule 4 — nom", groupe: 'Services' },
  formule_4_liste: { label: "Formule 4 — ce qui est inclus", groupe: 'Services' },
  textile_titre: { label: "Textiles — titre", groupe: 'Services' },
  textile_intro: { label: "Textiles — introduction", groupe: 'Services' },
  textile_etiquette: { label: "Textiles — intitule de la liste", groupe: 'Services' },
  textile_liste: { label: "Textiles — ce qui est traite", groupe: 'Services' },
  textile_photo_1: { label: "Textiles — photo 1", groupe: 'Services' },
  textile_legende_1: { label: "Textiles — legende 1", groupe: 'Services' },
  textile_photo_2: { label: "Textiles — photo 2", groupe: 'Services' },
  textile_legende_2: { label: "Textiles — legende 2", groupe: 'Services' },
  faq_q7: { label: "FAQ — question 7", groupe: 'FAQ' },
  faq_r7: { label: "FAQ — reponse 7", groupe: 'FAQ' },
  faq_q8: { label: "FAQ — question 8", groupe: 'FAQ' },
  faq_r8: { label: "FAQ — reponse 8", groupe: 'FAQ' },

  /* ---- Auto Wash 34 : questions frequentes ---- */
  faq_titre: { label: 'FAQ — titre', groupe: 'FAQ' },
  faq_intro: { label: 'FAQ — introduction', groupe: 'FAQ' },
  faq_q1: { label: 'FAQ — question 1', groupe: 'FAQ' },
  faq_r1: { label: 'FAQ — reponse 1', groupe: 'FAQ' },
  faq_q2: { label: 'FAQ — question 2', groupe: 'FAQ' },
  faq_r2: { label: 'FAQ — reponse 2', groupe: 'FAQ' },
  faq_q3: { label: 'FAQ — question 3', groupe: 'FAQ' },
  faq_r3: { label: 'FAQ — reponse 3', groupe: 'FAQ' },
  faq_q4: { label: 'FAQ — question 4', groupe: 'FAQ' },
  faq_r4: { label: 'FAQ — reponse 4', groupe: 'FAQ' },
  faq_q5: { label: 'FAQ — question 5', groupe: 'FAQ' },
  faq_r5: { label: 'FAQ — reponse 5', groupe: 'FAQ' },
  faq_q6: { label: 'FAQ — question 6', groupe: 'FAQ' },
  faq_r6: { label: 'FAQ — reponse 6', groupe: 'FAQ' },

  //  Redybat — carreleur, peintre et plaquiste a Lyon (2026-09-09).
  //  Chacun des quatre metiers a un texte ET une photo. La ligne image
  //  n'est pas facultative : sans elle, l'onglet Images de l'editeur
  //  annonce « aucune zone balisee » alors que le site tourne tres bien
  //  avec ses visuels statiques, et rien ne le signale.
  services_titre: { label: 'Nos metiers — titre', groupe: 'Services' },
  services_intro: { label: 'Nos metiers — introduction', groupe: 'Services' },
  service_carrelage_img: { label: 'Carrelage — photo', groupe: 'Services' },
  service_peinture_desc: { label: 'Peinture — description', groupe: 'Services' },
  service_peinture_img: { label: 'Peinture — photo', groupe: 'Services' },
  service_placo_desc: { label: 'Placo et cloisons — description', groupe: 'Services' },
  service_placo_img: { label: 'Placo et cloisons — photo', groupe: 'Services' },
  service_facade_desc: { label: 'Facade — description', groupe: 'Services' },
  service_facade_img: { label: 'Facade — photo', groupe: 'Services' },

  realisations_titre: { label: 'Realisations — titre', groupe: 'Preuve sociale' },
  realisations_intro: { label: 'Realisations — introduction', groupe: 'Preuve sociale' },
  realisation_1_avant: { label: 'Chantier 1 — photo avant', groupe: 'Preuve sociale' },
  realisation_1_apres: { label: 'Chantier 1 — photo apres', groupe: 'Preuve sociale' },
  realisation_2_avant: { label: 'Chantier 2 — photo avant', groupe: 'Preuve sociale' },
  realisation_2_apres: { label: 'Chantier 2 — photo apres', groupe: 'Preuve sociale' },
  realisation_2_lieu: { label: 'Chantier 2 — lieu', groupe: 'Preuve sociale' },

  //  Les deux bandes photo pleine largeur qui rythment la page.
  bande_chiffre: { label: 'Bande 1 — chiffre mis en avant', groupe: 'Expertise' },
  bande_titre: { label: 'Bande 1 — titre', groupe: 'Expertise' },
  bande_texte: { label: 'Bande 1 — texte', groupe: 'Expertise' },
  bande2_titre: { label: 'Bande 2 — titre', groupe: 'Engagement' },
  bande2_texte: { label: 'Bande 2 — texte', groupe: 'Engagement' },

  //  Sensi'Dyf — Georgia Gomez, psychopedagogue a Beziers (2026-09-09).
  //  `parcours_formations` est volontairement VIDE a la livraison : ses
  //  diplomes ne figurent nulle part sur ses pages publiques, et on ne
  //  devine pas les qualifications de quelqu'un qui travaille avec des
  //  enfants en situation de handicap.
  hero_publics: { label: 'Hero — publics accompagnes', groupe: 'Hero' },

  regard_titre: { label: 'Le regard — titre', groupe: 'A propos' },
  regard_intro: { label: 'Le regard — introduction', groupe: 'A propos' },
  regard_titre_1: { label: 'Le regard — volet 1, titre', groupe: 'A propos' },
  regard_texte_1: { label: 'Le regard — volet 1, texte', groupe: 'A propos' },
  regard_img_1: { label: 'Le regard — volet 1, photo', groupe: 'A propos' },
  regard_texte_2: { label: 'Le regard — volet 2, texte', groupe: 'A propos' },
  regard_img_2: { label: 'Le regard — volet 2, photo', groupe: 'A propos' },
  regard_texte_3: { label: 'Le regard — volet 3, texte', groupe: 'A propos' },
  regard_img_3: { label: 'Le regard — volet 3, photo', groupe: 'A propos' },

  bande1_titre: { label: 'Bande sensorielle — titre', groupe: 'Expertise' },
  bande1_texte: { label: 'Bande sensorielle — texte', groupe: 'Expertise' },

  service_caa: { label: 'CAA — description', groupe: 'Services' },
  service_aba: { label: 'Comportements defis — description', groupe: 'Services' },
  service_reflexes: { label: 'Reflexes archaiques — description', groupe: 'Services' },
  service_oro: { label: 'Reeducation oro-myo-faciale — description', groupe: 'Services' },
  service_ecole: { label: 'Coaching scolaire — description', groupe: 'Services' },
  service_parentalite: { label: 'Parentalite — description', groupe: 'Services' },
  service_mdph: { label: 'Demarches MDPH — description', groupe: 'Services' },
  service_materiel: { label: 'Materiel specialise — description', groupe: 'Services' },

  parcours_titre: { label: 'Qui je suis — titre', groupe: 'A propos' },
  parcours_citation: { label: 'Qui je suis — citation mise en avant', groupe: 'A propos' },
  parcours_texte_1: { label: 'Qui je suis — paragraphe 1', groupe: 'A propos' },
  parcours_texte_2: { label: 'Qui je suis — paragraphe 2', groupe: 'A propos' },
  parcours_texte_3: { label: 'Qui je suis — paragraphe 3', groupe: 'A propos' },
  parcours_photo: { label: 'Qui je suis — photo', groupe: 'A propos' },
  parcours_formations: { label: 'Qui je suis — formations et diplomes (A REMPLIR)', groupe: 'A propos' },

  financement_titre: { label: 'Financement — titre', groupe: 'Offre' },
  financement_soustitre: { label: 'Financement — sous-titre', groupe: 'Offre' },
  financement_texte_1: { label: 'Financement — paragraphe 1', groupe: 'Offre' },
  financement_texte_2: { label: 'Financement — paragraphe 2', groupe: 'Offre' },
  financement_texte_3: { label: 'Financement — paragraphe 3', groupe: 'Offre' },

  //  Le NUMERO se change a un seul endroit (`contact_telephone`,
  //  deja au manifeste), mais les deux LIENS qui l'appellent sont
  //  distincts : `tel:` et `sms:` ne se composent pas pareil. Les
  //  laisser hors manifeste, c'est laisser le client changer le
  //  numero affiche sans changer celui qui est compose.
  contact_lien_tel: { label: 'Lien d\'appel (tel:)', groupe: 'Footer' },
  contact_lien_sms: { label: 'Lien SMS (sms:)', groupe: 'Footer' },

  //  L'appel decouverte. Le libelle du bouton du hero et celui du
  //  formulaire sont deux cles distinctes mais doivent dire la
  //  MEME chose : deux libelles differents pour une seule action
  //  font hesiter au moment de cliquer.
  hero_cta: { label: 'Hero — libelle du bouton principal', groupe: 'Hero' },
  contact_bouton: { label: 'Formulaire — libelle du bouton', groupe: 'Footer' },
  appel_texte_1: { label: 'Appel decouverte — paragraphe 1', groupe: 'Offre' },
  appel_texte_2: { label: 'Appel decouverte — paragraphe 2', groupe: 'Offre' },

  //  Sensi'Dyf, deuxieme lot : prestations completes, lieu, tarifs et
  //  temoignages. Les trois temoignages sont livres VIDES : on
  //  n'invente pas d'avis sur un site d'accompagnement du handicap.
  presta_groupe_1: { label: 'Prestations — titre du groupe 1', groupe: 'Services' },
  presta_groupe_2: { label: 'Prestations — titre du groupe 2', groupe: 'Services' },
  services_note: { label: 'Prestations — note de bas de section', groupe: 'Services' },
  service_parcours: { label: 'Referente de parcours — description', groupe: 'Services' },
  service_polyhandicap: { label: 'Polyhandicap — description', groupe: 'Services' },
  service_habiletes: { label: 'Groupes d\'habiletes sociales — description', groupe: 'Services' },
  service_langage: { label: 'Ateliers de langage — description', groupe: 'Services' },
  service_bilan: { label: 'Bilan psychopedagogique — description', groupe: 'Services' },

  ou_titre: { label: 'Cabinet ou domicile — titre', groupe: 'A propos' },
  ou_intro: { label: 'Cabinet ou domicile — introduction', groupe: 'A propos' },
  ou_cabinet: { label: 'Le cabinet — description', groupe: 'A propos' },
  ou_domicile: { label: 'A domicile — description', groupe: 'A propos' },
  ou_pch: { label: 'PCH et CESU — description', groupe: 'A propos' },

  formations_titre: { label: 'Formations — titre', groupe: 'A propos' },
  formations_texte_1: { label: 'Formations — paragraphe 1', groupe: 'A propos' },
  formations_texte_2: { label: 'Formations — Haute Autorite de Sante', groupe: 'A propos' },

  tarifs_titre: { label: 'Tarifs — titre', groupe: 'Offre' },
  tarifs_intro: { label: 'Tarifs — introduction', groupe: 'Offre' },
  tarifs_note: { label: 'Tarifs — note (deplacements, groupes)', groupe: 'Offre' },
  tarif_1_nom: { label: 'Tarif 1 — intitule', groupe: 'Offre' },
  tarif_1_note: { label: 'Tarif 1 — precision', groupe: 'Offre' },
  tarif_1_prix: { label: 'Tarif 1 — prix', groupe: 'Offre' },
  tarif_2_nom: { label: 'Tarif 2 — intitule', groupe: 'Offre' },
  tarif_2_note: { label: 'Tarif 2 — precision', groupe: 'Offre' },
  tarif_2_prix: { label: 'Tarif 2 — prix', groupe: 'Offre' },
  tarif_3_nom: { label: 'Tarif 3 — intitule', groupe: 'Offre' },
  tarif_3_note: { label: 'Tarif 3 — precision', groupe: 'Offre' },
  tarif_3_prix: { label: 'Tarif 3 — prix', groupe: 'Offre' },
  tarif_4_nom: { label: 'Tarif 4 — intitule', groupe: 'Offre' },
  tarif_4_note: { label: 'Tarif 4 — precision', groupe: 'Offre' },
  tarif_4_prix: { label: 'Tarif 4 — prix', groupe: 'Offre' },

  financement_texte_4: { label: 'Financement — devis et factures', groupe: 'Offre' },
  financement_texte_5: { label: 'Financement — moyens de paiement', groupe: 'Offre' },

  temoignages_titre: { label: 'Temoignages — titre', groupe: 'Preuve sociale' },
  temoignages_intro: { label: 'Temoignages — introduction', groupe: 'Preuve sociale' },
  temoignages_lien: { label: 'Temoignages — lien vers la fiche Google', groupe: 'Preuve sociale' },
  temoignage_1_texte: { label: 'Temoignage 1 — texte', groupe: 'Preuve sociale' },
  temoignage_1_nom: { label: 'Temoignage 1 — signature', groupe: 'Preuve sociale' },
  temoignage_2_texte: { label: 'Temoignage 2 — texte', groupe: 'Preuve sociale' },
  temoignage_2_nom: { label: 'Temoignage 2 — signature', groupe: 'Preuve sociale' },
  temoignage_1_source: { label: 'Temoignage 1 — provenance', groupe: 'Preuve sociale' },
  temoignage_2_source: { label: 'Temoignage 2 — provenance', groupe: 'Preuve sociale' },
  temoignages_appel_titre: { label: 'Laisser un avis — titre', groupe: 'Preuve sociale' },
  temoignages_appel_texte: { label: 'Laisser un avis — texte', groupe: 'Preuve sociale' },

  bande_tarifs_titre: { label: 'Bande avant les tarifs — titre', groupe: 'Offre' },
  bande_tarifs_texte: { label: 'Bande avant les tarifs — texte', groupe: 'Offre' },

  //  KSM : les avis Google poses sous la carte de localisation.
  //  Les textes sont ceux des clients, releves sur la fiche : les
  //  rendre modifiables permet de les remplacer par des avis plus
  //  recents, pas d'en inventer.
  avis_titre: { label: 'Avis — titre de la section', groupe: 'Preuve sociale' },
  avis_note: { label: 'Avis — note globale', groupe: 'Preuve sociale' },
  avis_nombre: { label: 'Avis — nombre d\'avis', groupe: 'Preuve sociale' },
  avis_lien: { label: 'Avis — bouton vers la fiche Google', groupe: 'Preuve sociale' },
  avis_1_texte: { label: 'Avis 1 — texte', groupe: 'Preuve sociale' },
  avis_1_nom: { label: 'Avis 1 — signature', groupe: 'Preuve sociale' },
  avis_2_texte: { label: 'Avis 2 — texte', groupe: 'Preuve sociale' },
  avis_2_nom: { label: 'Avis 2 — signature', groupe: 'Preuve sociale' },
  avis_3_texte: { label: 'Avis 3 — texte', groupe: 'Preuve sociale' },
  avis_3_nom: { label: 'Avis 3 — signature', groupe: 'Preuve sociale' },

  //  Sensi'Dyf, troisieme lot : le contenu redige par Georgia
  //  elle-meme, envoye le 2026-09-10. La grande section CAA, la
  //  sensorialite, ses sept familles de formations, la galerie de
  //  ses propres photos et le contact WhatsApp.
  caa_surtitre: { label: 'CAA — surtitre', groupe: 'Services' },
  caa_titre: { label: 'CAA — titre', groupe: 'Services' },
  caa_intro: { label: 'CAA — phrase d’accroche', groupe: 'Services' },
  caa_texte_1: { label: 'CAA — paragraphe 1', groupe: 'Services' },
  caa_texte_2: { label: 'CAA — paragraphe 2', groupe: 'Services' },
  caa_supports_titre: { label: 'CAA — intro de la liste des supports', groupe: 'Services' },
  caa_outil_1: { label: 'CAA — support 1', groupe: 'Services' },
  caa_outil_2: { label: 'CAA — support 2', groupe: 'Services' },
  caa_outil_3: { label: 'CAA — support 3', groupe: 'Services' },
  caa_outil_4: { label: 'CAA — support 4', groupe: 'Services' },
  caa_texte_3: { label: 'CAA — outils numériques', groupe: 'Services' },
  caa_photo: { label: 'CAA — photo du tableau de langage', groupe: 'Services' },
  caa_relation_titre: { label: 'CAA — titre « la relation »', groupe: 'Services' },
  caa_relation_1: { label: 'CAA — relation, paragraphe 1', groupe: 'Services' },
  caa_relation_2: { label: 'CAA — relation, paragraphe 2', groupe: 'Services' },
  caa_relation_3: { label: 'CAA — relation, paragraphe 3', groupe: 'Services' },
  caa_ecoles_titre: { label: 'CAA — titre « écoles et structures »', groupe: 'Services' },
  caa_ecoles_texte: { label: 'CAA — écoles et structures', groupe: 'Services' },
  signature: { label: 'Phrase signature', groupe: 'A propos' },
  sens_surtitre: { label: 'Sensorialité — surtitre', groupe: 'Services' },
  sens_titre: { label: 'Sensorialité — titre', groupe: 'Services' },
  sens_intro: { label: 'Sensorialité — phrase d’accroche', groupe: 'Services' },
  sens_texte_1: { label: 'Sensorialité — paragraphe 1', groupe: 'Services' },
  sens_texte_2: { label: 'Sensorialité — paragraphe 2', groupe: 'Services' },
  sens_texte_3: { label: 'Sensorialité — paragraphe 3', groupe: 'Services' },
  sens_photo: { label: 'Sensorialité — photo du haut', groupe: 'Services' },
  sens_photo_2: { label: 'Sensorialité — photo du bas', groupe: 'Services' },
  form_1_titre: { label: 'Formation 1 — intitulé (Autisme et TND)', groupe: 'A propos' },
  form_1_texte: { label: 'Formation 1 — détail', groupe: 'A propos' },
  form_2_titre: { label: 'Formation 2 — intitulé (Analyse du comportement)', groupe: 'A propos' },
  form_2_texte: { label: 'Formation 2 — détail', groupe: 'A propos' },
  form_3_titre: { label: 'Formation 3 — intitulé (Communication et langage)', groupe: 'A propos' },
  form_3_texte: { label: 'Formation 3 — détail', groupe: 'A propos' },
  form_4_titre: { label: 'Formation 4 — intitulé (Sensorialité et psychomotricité)', groupe: 'A propos' },
  form_4_texte: { label: 'Formation 4 — détail', groupe: 'A propos' },
  form_5_titre: { label: 'Formation 5 — intitulé (Émotions et régulation)', groupe: 'A propos' },
  form_5_texte: { label: 'Formation 5 — détail', groupe: 'A propos' },
  form_6_titre: { label: 'Formation 6 — intitulé (Relation et outils)', groupe: 'A propos' },
  form_6_texte: { label: 'Formation 6 — détail', groupe: 'A propos' },
  form_7_titre: { label: 'Formation 7 — intitulé (Formation en cours)', groupe: 'A propos' },
  form_7_texte: { label: 'Formation 7 — détail', groupe: 'A propos' },
  formations_texte_3: { label: 'Formations — conclusion', groupe: 'A propos' },
  galerie_surtitre: { label: 'Galerie — surtitre', groupe: 'Images' },
  galerie_titre: { label: 'Galerie — titre', groupe: 'Images' },
  galerie_intro: { label: 'Galerie — introduction', groupe: 'Images' },
  galerie_01: { label: 'Galerie — photo 1', groupe: 'Images' },
  galerie_02: { label: 'Galerie — photo 2', groupe: 'Images' },
  galerie_03: { label: 'Galerie — photo 3', groupe: 'Images' },
  galerie_04: { label: 'Galerie — photo 4', groupe: 'Images' },
  galerie_05: { label: 'Galerie — photo 5', groupe: 'Images' },
  galerie_06: { label: 'Galerie — photo 6', groupe: 'Images' },
  galerie_07: { label: 'Galerie — photo 7', groupe: 'Images' },
  galerie_08: { label: 'Galerie — photo 8', groupe: 'Images' },
  galerie_09: { label: 'Galerie — photo 9', groupe: 'Images' },
  galerie_10: { label: 'Galerie — photo 10', groupe: 'Images' },
  galerie_11: { label: 'Galerie — photo 11', groupe: 'Images' },
  galerie_12: { label: 'Galerie — photo 12', groupe: 'Images' },
  galerie_13: { label: 'Galerie — photo 13', groupe: 'Images' },
  galerie_14: { label: 'Galerie — photo 14', groupe: 'Images' },
  contact_lien_whatsapp: { label: 'Contact — lien WhatsApp', groupe: 'Contact' },

  //  Latitude 43, brasserie a Magalas. Refonte du site
  //  WordPress existant, presentee a M. Clapier le 2026-09-11.
  hero_photo: { label: 'Hero — photo de fond', groupe: 'Hero' },
  hero_coord: { label: 'Hero — la ligne de coordonnées', groupe: 'Hero' },
  hero_sous: { label: 'Hero — sous-titre', groupe: 'Hero' },
  hero_texte: { label: 'Hero — phrase d’accroche', groupe: 'Hero' },
  bandeau_service: { label: 'Bandeau — horaires de service', groupe: 'Horaires' },
  bandeau_emporter: { label: 'Bandeau — vente à emporter', groupe: 'Horaires' },
  bandeau_adresse: { label: 'Bandeau — adresse', groupe: 'Contact' },
  histoire_titre: { label: 'La maison — titre', groupe: 'A propos' },
  histoire_citation: { label: 'La maison — citation des gérants', groupe: 'A propos' },
  histoire_signature: { label: 'La maison — signature de la citation', groupe: 'A propos' },
  histoire_texte_1: { label: 'La maison — paragraphe 1', groupe: 'A propos' },
  histoire_texte_2: { label: 'La maison — paragraphe 2', groupe: 'A propos' },
  histoire_photo: { label: 'La maison — photo', groupe: 'A propos' },
  fait_1: { label: 'Chiffre 1 — année d’ouverture', groupe: 'A propos' },
  fait_2: { label: 'Chiffre 2 — expérience du chef', groupe: 'A propos' },
  fait_3: { label: 'Chiffre 3 — part de fait maison', groupe: 'A propos' },
  fait_4: { label: 'Chiffre 4 — domaines à la carte', groupe: 'A propos' },
  carte_titre: { label: 'La carte — titre', groupe: 'Carte' },
  carte_intro: { label: 'La carte — introduction', groupe: 'Carte' },
  carte_note: { label: 'La carte — moyens de paiement', groupe: 'Carte' },
  cuisine_titre: { label: 'La cuisine — titre', groupe: 'A propos' },
  cuisine_citation: { label: 'La cuisine — citation', groupe: 'A propos' },
  cuisine_texte_1: { label: 'La cuisine — paragraphe 1', groupe: 'A propos' },
  cuisine_texte_2: { label: 'La cuisine — paragraphe 2', groupe: 'A propos' },
  cuisine_photo: { label: 'La cuisine — photo', groupe: 'A propos' },
  lieu_titre: { label: 'Le lieu — titre', groupe: 'Images' },
  lieu_intro: { label: 'Le lieu — introduction', groupe: 'Images' },
  galerie_1: { label: 'Galerie — photo 1 (la terrasse)', groupe: 'Images' },
  galerie_2: { label: 'Galerie — photo 2 (les vins)', groupe: 'Images' },
  galerie_3: { label: 'Galerie — photo 3 (la salle (bois))', groupe: 'Images' },
  galerie_4: { label: 'Galerie — photo 4 (les planches)', groupe: 'Images' },
  galerie_5: { label: 'Galerie — photo 5 (la salle (clair))', groupe: 'Images' },
  galerie_6: { label: 'Galerie — photo 6 (le village)', groupe: 'Images' },
  galerie_7: { label: 'Galerie — photo 7 (un plat)', groupe: 'Images' },
  galerie_8: { label: 'Galerie — photo 8 (la cuisine)', groupe: 'Images' },
  aussi_titre: { label: 'Aussi chez nous — titre', groupe: 'Services' },
  aussi_photo_1: { label: 'Aussi chez nous — photo (à emporter)', groupe: 'Services' },
  aussi_titre_1: { label: 'Aussi chez nous — titre (à emporter)', groupe: 'Services' },
  aussi_texte_1: { label: 'Aussi chez nous — texte (à emporter)', groupe: 'Services' },
  aussi_photo_2: { label: 'Aussi chez nous — photo (les soirées)', groupe: 'Services' },
  aussi_titre_2: { label: 'Aussi chez nous — titre (les soirées)', groupe: 'Services' },
  aussi_texte_2: { label: 'Aussi chez nous — texte (les soirées)', groupe: 'Services' },
  aussi_photo_3: { label: 'Aussi chez nous — photo (le bar)', groupe: 'Services' },
  aussi_titre_3: { label: 'Aussi chez nous — titre (le bar)', groupe: 'Services' },
  aussi_texte_3: { label: 'Aussi chez nous — texte (le bar)', groupe: 'Services' },
  aussi_fidelite: { label: 'Aussi chez nous — carte de fidélité', groupe: 'Services' },
  venir_titre: { label: 'Nous trouver — titre', groupe: 'Contact' },
  venir_intro: { label: 'Nous trouver — introduction', groupe: 'Contact' },
  venir_info_1: { label: 'Nous trouver — info 1 (service en salle)', groupe: 'Contact' },
  venir_info_2: { label: 'Nous trouver — info 2 (moyens de paiement)', groupe: 'Contact' },
  venir_info_3: { label: 'Nous trouver — info 3 (terrasse et options)', groupe: 'Contact' },
  venir_info_4: { label: 'Nous trouver — info 4 (vente à emporter)', groupe: 'Contact' },
  pied_description: { label: 'Pied de page — description', groupe: 'Pied de page' }
};

export const GROUP_ORDER = [
  'Hero', 'Services', 'À propos', 'Engagement', 'Expertise', 'Preuve sociale',
  'Offre', 'FAQ', 'Horaires', 'Footer', 'Autres'
];
